### ISSUE TITLE
Netzwerk

### ISSUE THREAD

**Issue by patagonaa** [opendata-heilbronn/farmbot#34]
Was brauchen wir für Internet/Netzwerk auf der Buga?
- [ ] Netzwerk
    - [x] aktuell vorhandene Geräte mit Router verbinden
    - [ ] wenn Bedarf: Switch einbauen
    - [ ] Power Save bei Nacht, um Solarsystem zu entlasten (Extrembeispiel: https://github.com/zhangjingye03/openwrt_deep_night_sleep)
- [ ] Internet
    - [ ] Richtfunk #25 
    - [x] UMTS (so, dass es dauerhaft funktioniert)
    - [x] Privates WLAN
- [x] VPN
    - [x] Server einrichten
    - [x] Client einrichten

**Comment by Techbeard** [comment]
Alles funktioniert
