### ISSUE TITLE
Strom

### ISSUE THREAD

**Issue by patagonaa** [opendata-heilbronn/farmbot#35]
- [x] Akkus auf Buga aufstellen
- [x] Solarpanels auf dem Dach montieren
- [ ] Verdrahtung
    - [x] Akkus an Laderegler
    - [x] Stromverteiler, Relais usw. (siehe Wiki)
    - [ ] Netzteil
    - [ ] Leistungsüberwachung Verbrauch (?)
    - [ ] Einschaltstrombegrenzung

**Comment by Techbeard** [comment]
Stromnetzt funktioniert und vorhanden
